// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: internal/callruntime/v1/callruntime.proto

package callruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CallRuntimeService_EnsureSession_FullMethodName         = "/zvonilka.internal.callruntime.v1.CallRuntimeService/EnsureSession"
	CallRuntimeService_JoinSession_FullMethodName           = "/zvonilka.internal.callruntime.v1.CallRuntimeService/JoinSession"
	CallRuntimeService_PublishDescription_FullMethodName    = "/zvonilka.internal.callruntime.v1.CallRuntimeService/PublishDescription"
	CallRuntimeService_PublishCandidate_FullMethodName      = "/zvonilka.internal.callruntime.v1.CallRuntimeService/PublishCandidate"
	CallRuntimeService_UpdateParticipant_FullMethodName     = "/zvonilka.internal.callruntime.v1.CallRuntimeService/UpdateParticipant"
	CallRuntimeService_AcknowledgeAdaptation_FullMethodName = "/zvonilka.internal.callruntime.v1.CallRuntimeService/AcknowledgeAdaptation"
	CallRuntimeService_SessionStats_FullMethodName          = "/zvonilka.internal.callruntime.v1.CallRuntimeService/SessionStats"
	CallRuntimeService_LeaveSession_FullMethodName          = "/zvonilka.internal.callruntime.v1.CallRuntimeService/LeaveSession"
	CallRuntimeService_CloseSession_FullMethodName          = "/zvonilka.internal.callruntime.v1.CallRuntimeService/CloseSession"
)

// CallRuntimeServiceClient is the client API for CallRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallRuntimeServiceClient interface {
	EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*EnsureSessionResponse, error)
	JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*JoinSessionResponse, error)
	PublishDescription(ctx context.Context, in *PublishDescriptionRequest, opts ...grpc.CallOption) (*PublishDescriptionResponse, error)
	PublishCandidate(ctx context.Context, in *PublishCandidateRequest, opts ...grpc.CallOption) (*PublishCandidateResponse, error)
	UpdateParticipant(ctx context.Context, in *UpdateParticipantRequest, opts ...grpc.CallOption) (*UpdateParticipantResponse, error)
	AcknowledgeAdaptation(ctx context.Context, in *AcknowledgeAdaptationRequest, opts ...grpc.CallOption) (*AcknowledgeAdaptationResponse, error)
	SessionStats(ctx context.Context, in *SessionStatsRequest, opts ...grpc.CallOption) (*SessionStatsResponse, error)
	LeaveSession(ctx context.Context, in *LeaveSessionRequest, opts ...grpc.CallOption) (*LeaveSessionResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type callRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallRuntimeServiceClient(cc grpc.ClientConnInterface) CallRuntimeServiceClient {
	return &callRuntimeServiceClient{cc}
}

func (c *callRuntimeServiceClient) EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*EnsureSessionResponse, error) {
	out := new(EnsureSessionResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_EnsureSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*JoinSessionResponse, error) {
	out := new(JoinSessionResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_JoinSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) PublishDescription(ctx context.Context, in *PublishDescriptionRequest, opts ...grpc.CallOption) (*PublishDescriptionResponse, error) {
	out := new(PublishDescriptionResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_PublishDescription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) PublishCandidate(ctx context.Context, in *PublishCandidateRequest, opts ...grpc.CallOption) (*PublishCandidateResponse, error) {
	out := new(PublishCandidateResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_PublishCandidate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) UpdateParticipant(ctx context.Context, in *UpdateParticipantRequest, opts ...grpc.CallOption) (*UpdateParticipantResponse, error) {
	out := new(UpdateParticipantResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_UpdateParticipant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) AcknowledgeAdaptation(ctx context.Context, in *AcknowledgeAdaptationRequest, opts ...grpc.CallOption) (*AcknowledgeAdaptationResponse, error) {
	out := new(AcknowledgeAdaptationResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_AcknowledgeAdaptation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) SessionStats(ctx context.Context, in *SessionStatsRequest, opts ...grpc.CallOption) (*SessionStatsResponse, error) {
	out := new(SessionStatsResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_SessionStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) LeaveSession(ctx context.Context, in *LeaveSessionRequest, opts ...grpc.CallOption) (*LeaveSessionResponse, error) {
	out := new(LeaveSessionResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_LeaveSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callRuntimeServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, CallRuntimeService_CloseSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallRuntimeServiceServer is the server API for CallRuntimeService service.
// All implementations must embed UnimplementedCallRuntimeServiceServer
// for forward compatibility
type CallRuntimeServiceServer interface {
	EnsureSession(context.Context, *EnsureSessionRequest) (*EnsureSessionResponse, error)
	JoinSession(context.Context, *JoinSessionRequest) (*JoinSessionResponse, error)
	PublishDescription(context.Context, *PublishDescriptionRequest) (*PublishDescriptionResponse, error)
	PublishCandidate(context.Context, *PublishCandidateRequest) (*PublishCandidateResponse, error)
	UpdateParticipant(context.Context, *UpdateParticipantRequest) (*UpdateParticipantResponse, error)
	AcknowledgeAdaptation(context.Context, *AcknowledgeAdaptationRequest) (*AcknowledgeAdaptationResponse, error)
	SessionStats(context.Context, *SessionStatsRequest) (*SessionStatsResponse, error)
	LeaveSession(context.Context, *LeaveSessionRequest) (*LeaveSessionResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	mustEmbedUnimplementedCallRuntimeServiceServer()
}

// UnimplementedCallRuntimeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCallRuntimeServiceServer struct {
}

func (UnimplementedCallRuntimeServiceServer) EnsureSession(context.Context, *EnsureSessionRequest) (*EnsureSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureSession not implemented")
}
func (UnimplementedCallRuntimeServiceServer) JoinSession(context.Context, *JoinSessionRequest) (*JoinSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedCallRuntimeServiceServer) PublishDescription(context.Context, *PublishDescriptionRequest) (*PublishDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishDescription not implemented")
}
func (UnimplementedCallRuntimeServiceServer) PublishCandidate(context.Context, *PublishCandidateRequest) (*PublishCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishCandidate not implemented")
}
func (UnimplementedCallRuntimeServiceServer) UpdateParticipant(context.Context, *UpdateParticipantRequest) (*UpdateParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParticipant not implemented")
}
func (UnimplementedCallRuntimeServiceServer) AcknowledgeAdaptation(context.Context, *AcknowledgeAdaptationRequest) (*AcknowledgeAdaptationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeAdaptation not implemented")
}
func (UnimplementedCallRuntimeServiceServer) SessionStats(context.Context, *SessionStatsRequest) (*SessionStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionStats not implemented")
}
func (UnimplementedCallRuntimeServiceServer) LeaveSession(context.Context, *LeaveSessionRequest) (*LeaveSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveSession not implemented")
}
func (UnimplementedCallRuntimeServiceServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedCallRuntimeServiceServer) mustEmbedUnimplementedCallRuntimeServiceServer() {}

// UnsafeCallRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallRuntimeServiceServer will
// result in compilation errors.
type UnsafeCallRuntimeServiceServer interface {
	mustEmbedUnimplementedCallRuntimeServiceServer()
}

func RegisterCallRuntimeServiceServer(s grpc.ServiceRegistrar, srv CallRuntimeServiceServer) {
	s.RegisterService(&CallRuntimeService_ServiceDesc, srv)
}

func _CallRuntimeService_EnsureSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).EnsureSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_EnsureSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).EnsureSession(ctx, req.(*EnsureSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_JoinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).JoinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_JoinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).JoinSession(ctx, req.(*JoinSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_PublishDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).PublishDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_PublishDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).PublishDescription(ctx, req.(*PublishDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_PublishCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).PublishCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_PublishCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).PublishCandidate(ctx, req.(*PublishCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_UpdateParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).UpdateParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_UpdateParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).UpdateParticipant(ctx, req.(*UpdateParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_AcknowledgeAdaptation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAdaptationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).AcknowledgeAdaptation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_AcknowledgeAdaptation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).AcknowledgeAdaptation(ctx, req.(*AcknowledgeAdaptationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_SessionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).SessionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_SessionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).SessionStats(ctx, req.(*SessionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_LeaveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).LeaveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_LeaveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).LeaveSession(ctx, req.(*LeaveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallRuntimeService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallRuntimeServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallRuntimeService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallRuntimeServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallRuntimeService_ServiceDesc is the grpc.ServiceDesc for CallRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zvonilka.internal.callruntime.v1.CallRuntimeService",
	HandlerType: (*CallRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureSession",
			Handler:    _CallRuntimeService_EnsureSession_Handler,
		},
		{
			MethodName: "JoinSession",
			Handler:    _CallRuntimeService_JoinSession_Handler,
		},
		{
			MethodName: "PublishDescription",
			Handler:    _CallRuntimeService_PublishDescription_Handler,
		},
		{
			MethodName: "PublishCandidate",
			Handler:    _CallRuntimeService_PublishCandidate_Handler,
		},
		{
			MethodName: "UpdateParticipant",
			Handler:    _CallRuntimeService_UpdateParticipant_Handler,
		},
		{
			MethodName: "AcknowledgeAdaptation",
			Handler:    _CallRuntimeService_AcknowledgeAdaptation_Handler,
		},
		{
			MethodName: "SessionStats",
			Handler:    _CallRuntimeService_SessionStats_Handler,
		},
		{
			MethodName: "LeaveSession",
			Handler:    _CallRuntimeService_LeaveSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _CallRuntimeService_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/callruntime/v1/callruntime.proto",
}
