ALTER TABLE {{schema}}.call_participants
	ADD COLUMN IF NOT EXISTS hand_raised BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS raised_hand_at TIMESTAMPTZ NULL,
	ADD COLUMN IF NOT EXISTS host_muted_audio BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS host_muted_video BOOLEAN NOT NULL DEFAULT FALSE;
